name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24

dependency_overrides:
  dartx: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.6
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
